# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'KarbantartasNaplo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KarbantartasNaplo
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'Charts', '~> 3.4.0'
  pod 'UICountingLabel', '~> 1.4.1'

  target 'KarbantartasNaploTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KarbantartasNaploUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
